local tree_climber = require('tree-climber')
local keyopts = { noremap = true, silent = true }
vim.keymap.set({ 'n', 'v', 'o' }, 'H', tree_climber.goto_parent, keyopts)
vim.keymap.set({ 'n', 'v', 'o' }, 'L', tree_climber.goto_child, keyopts)
vim.keymap.set({ 'n', 'v', 'o' }, 'J', tree_climber.goto_next, keyopts)
vim.keymap.set({ 'n', 'v', 'o' }, 'K', tree_climber.goto_prev, keyopts)
vim.keymap.set({ 'v', 'o' }, 'in', tree_climber.select_node, keyopts)
vim.keymap.set('n', '<c-k>', tree_climber.swap_prev, keyopts)
vim.keymap.set('n', '<c-j>', tree_climber.swap_next, keyopts)
vim.keymap.set('n', '<c-h>', tree_climber.highlight_node, keyopts)
